server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true

appDescription: "Wallet Service"
appVersion: "1.0.0"
